# The URL the site will be built for
base_url = "https://site-here"
title = "Halcyon"
description = "A simple blog for me to write my thoughts"
author = "Lorem"

compile_sass = true

build_search_index = false

taxonomies = [
    { name = "tags" },
]

# Generates info for RSS readers
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"
bottom_footnotes = true

[extra]
# Put all your custom variables here'
links = [
    { title = "Github", href = "https://github.com" },
]
